- hosts: tag_App_kube
  remote_user: admin
  become: yes
  become_user: root
  collections: 
    - smc181002.k8s
  roles:
    - common

- hosts: tag_Name_kube_master
  remote_user: admin
  become: yes
  become_user: root
  collections: 
    - smc181002.k8s
  tasks:
    - name: run master role
      include_role:
        name: master
      vars: 
        net_name: "10.240.0.0/16"

    - set_fact:
        join_command: "{{ jointoken }}"
    - debug:
        msg: "{{hostvars[groups['tag_Name_kube_master'][0]]['join_command']['stdout']}}"

- hosts: tag_Name_kube_slave
  remote_user: admin
  become: yes
  become_user: root
  collections: 
    - smc181002.k8s
  tasks: 
    - name: slave config
      include_role:
        name: slave
      vars: 
        join_command: "{{hostvars[groups['tag_Name_kube_master'][0]]['join_command']['stdout']}}"
