- hosts: localhost
  collections:
    - smc181002.k8s
  tasks:
    - name: launch nodes
      include_role:
        name: provision
      vars:
        key_name: k8s-mongodb
        sec_grp: launch-wizard-3
        ami_id: ami-01216e7612243e0ef
        os_type: t3.medium

    - set_fact:
        instances: "{{ kube_ec2_master.instances + kube_ec2_slave.instances }}"

    - name: wait for ssh to start
      wait_for:
        host: "{{item.public_dns_name}}"
        port: 22
        state: started
      loop: "{{instances}}"
